apiVersion: v1
kind: Service
metadata:
  name: auto-scaler
  labels:
    app: auto-scaler
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
  selector:
    app: auto-scaler
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auto-scaler
  labels:
    app: auto-scaler
spec:
  selector:
    matchLabels:
      app: auto-scaler
  replicas: 1
  template:
    metadata:
      labels:
        app: auto-scaler
    spec:
      serviceAccountName: nodepool-autoscale
      containers:
      - name: auto-scaler
        image: lostinbrittany/ovhcloud-k8s-autoscaling_autoscaler-example:0.0.2
        resources:
          limits:
            cpu: 300m
            memory: 100Mi
          requests:
            cpu: 150m
            memory: 50Mi
        ports:
        - containerPort: 8080        
        env:
          - name: K8S
            value: https://kubernetes
          - name: TOKEN
            value: /var/run/secrets/kubernetes.io/serviceaccount/token
          - name: CA_CERT
            value: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
          - name: NODE_TLS_REJECT_UNAUTHORIZED
            value: '0'
        