apiVersion: v1
kind: ServiceAccount
metadata:
  name: nodepool-autoscale
  namespace: default
---    
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nodepool-autoscale
  labels:
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["namespaces","nodes", "nodes/status"]
  verbs: ["list", "get"]
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods"]
  verbs: ["list", "get","create","delete","patch"]
- apiGroups: ["apps"] # "" indicates the core API group
  resources: ["deployments"]
  verbs: ["list", "get","create","delete","patch"]  
- apiGroups: ["kube.cloud.ovh.com"]
  resources: ["nodepools","nodepools/status","nodepools/patch"]
  verbs: ["list","get", "patch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods", "nodes", "nodes/status"]
  verbs: ["list", "get"]
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: nodepool-autoscale
subjects:
- kind: ServiceAccount
  name: nodepool-autoscale
  namespace: default
roleRef:
  kind: ClusterRole
  name: nodepool-autoscale
  apiGroup: rbac.authorization.k8s.io